import "./globals.css";
import Navbar from "./components/Navbar";
import AnimatedCursor from "./components/AnimatedCursor";
import AppWalletProvider from "./components/AppWalletProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AnimatedCursor />
      <AppWalletProvider>
      <Navbar/>
        {children}
        </AppWalletProvider>

        </body>
    </html>
  );
}
